apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-ipatime-route
spec:
  host: isipatime.apps.sandbox-m3.1530.p1.openshiftapps.com
  to:
    kind: Service
    name: nginx-ipatime
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
